# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# YAML configuration for Bigfish batch processing (for HCRv3)
# Modified: 2023.05.22
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

# - - - - - General configuration
## The number of processes in the pool of processes
number_of_workers: 2
## The directory with images
input_pattern: C:\Users\sjoh4548\Desktop\New folder\*.tif
## The directory where the big-fish output npz or quality control files will be stored
## These directories will be created if they don't exist
output_dir: C:\Users\sjoh4548\Desktop\New folder\bf_output
output_qc_dir: C:\Users\sjoh4548\Desktop\New folder\bf_output_qc

# - - - - - Bigfish configuration
## Image voxel size and PSF parameters
voxel_size_yx: 65
voxel_size_z: 200
ex: 570
em: 610
NA: 1.45
RI: 1.45
microscope: confocal
## Background subtraction radius in pixels
bg_radius: 5
## The channels for which to run the processing (0-based)
## Use [2, 3] format to quantify two HCRv3 channels 
channels: [2] 
## Bigfish single-spot detection parameters
auto_threshold: True
auto_bailout_mode: True
auto_bailout_spot_limit: 100
## Set up manual thresholds if not using auto-thresholding
HCRv3_ch1: 2
HCRv3_ch1_thresh: 50
HCRv3_ch2: 3
HCRv3_ch2_thresh: 30
## Do subpixel fitting?
subpixel_fitting_mode: False